/**
 * Attention: Generated source! Do not modify by hand!
 * Generated by: Merode Code Generator 2.0
 */
package ui.tabs.tables.views;



import handlers.MerodeMainEventHandler;

import javax.swing.*;
import javax.swing.border.TitledBorder;

import ui.tabs.tables.ObjectTable;

import driver.MerodeMainEventHandlerGui;

import java.awt.event.*;
import java.awt.*;





/**
 * Abstract superclass for a frame that has
 * - an attribute table
 * - tables referencing to master and dependent object sets
 * - a button OK
 */
@SuppressWarnings("serial")
public abstract class ObjectViewPanel extends JPanel {
	
    protected MerodeMainEventHandlerGui main_frame;
    protected MerodeMainEventHandler main_handler;
    protected Object object;
    
    protected JPanel attributes_p;
    protected JPanel associated_objects_p;
    protected JPanel masters_p;
    protected JPanel dependents_p;
    
    public ObjectTable table;
    
    public ObjectViewPanel(MerodeMainEventHandlerGui main_f, MerodeMainEventHandler main_h, String title, Object obj) {
        //super(title);
        main_frame = main_f;
        main_handler = main_h;
        object = obj;
    
        setLayout (new BoxLayout(this, BoxLayout.Y_AXIS));
        //setSize(300, 300);
        buildFrame(this);
        //temporarily removed due to multiple view instances opening issue
        //constructOkButton(this); 
    }

    protected void buildFrame(Container p) {
        constructAttributesPane (p);
        completeAttributesPane ();
        
        JPanel obj_p = new JPanel();
        obj_p.setLayout (new BoxLayout(obj_p, BoxLayout.X_AXIS));
    
        associated_objects_p = new JPanel();
        masters_p = new JPanel(new BoxLayout(masters_p, BoxLayout.Y_AXIS));
        dependents_p = new JPanel(new BoxLayout(dependents_p, BoxLayout.Y_AXIS));
        
        associated_objects_p.setLayout(new BoxLayout(associated_objects_p, BoxLayout.Y_AXIS));
        masters_p.setLayout(new BoxLayout(masters_p, BoxLayout.Y_AXIS));
        dependents_p.setLayout(new BoxLayout(dependents_p, BoxLayout.Y_AXIS));
        
        
        associated_objects_p.setBorder(BorderFactory.createCompoundBorder(
        		BorderFactory.createTitledBorder(" Associated Objects "),
                BorderFactory
                    .createEmptyBorder(5, 5, 5, 5)));
        
        associated_objects_p.add(masters_p);
        associated_objects_p.add(dependents_p);
        
        obj_p.add (associated_objects_p);
        obj_p.add (Box.createHorizontalGlue());
    
        p.add (obj_p, BorderLayout.NORTH);
        
        constructMasterTables();
        constructDependentTables();
    }    

    protected abstract void completeAttributesPane ();
    protected abstract void constructMasterTables ();
	protected abstract void constructDependentTables ();
    
    private void constructAttributesPane(Container p) {
        JPanel top_p = new JPanel();
        top_p.setLayout (new BoxLayout(top_p, BoxLayout.X_AXIS));
    
        attributes_p = new JPanel();
        attributes_p.setLayout (new BoxLayout(attributes_p, BoxLayout.Y_AXIS));
        attributes_p.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createTitledBorder("Attributes"),
                BorderFactory
                    .createEmptyBorder(5, 5, 5, 5)));
        
        top_p.add (attributes_p);
        top_p.add (Box.createHorizontalGlue());
    
        p.add (top_p, BorderLayout.NORTH);
    }
    
    protected void constructOkButton(Container p) {
        JPanel button_p = new JPanel();
        button_p.setBorder(BorderFactory.createEmptyBorder(5,5,5,5));
        button_p.setLayout (new BoxLayout(button_p, BoxLayout.X_AXIS));
    
        button_p.add (Box.createHorizontalGlue());
        final JButton ok_b = new JButton("Ok");
        ok_b.addActionListener ( new ActionListener() {
            public void actionPerformed (ActionEvent event) {
                //dispose();
            	((JFrame) ok_b.getRootPane().getParent()).dispose();
            }
        });
        button_p.add (ok_b);
        button_p.add (Box.createHorizontalGlue());
    
        p.add (button_p);
    }
    
}
