/**
 * Attention: Generated source! Do not modify by hand!
 * Generated by: Merode Code Generator 2.0
 */
package ui.tabs.tables.views;

import handlers.MerodeMainEventHandler;

import javax.swing.*;
import javax.swing.border.*;
import java.awt.event.*;
import java.awt.*;

import java.util.*;

import javax.swing.event.*;
import javax.swing.table.*;


/**
 * Class to render cells that represent a reference to a collection of objects.
 * It contains:
 * - A combobox
 * - A button to show the details of the selected object
 */
public class ObjectViewRenderer extends JPanel implements TableCellRenderer {
    private ArrayList objects;
    private MerodeMainEventHandler main_handler;
    private JTable table;

	public ObjectViewRenderer( 
  			MerodeMainEventHandler main_h, 
				ArrayList obj, JTable tab) {
		setLayout(new BoxLayout(this, BoxLayout.X_AXIS));
		//JComboBox combo = new JComboBox();
		//combo.addItem("Objects");
		//add(combo);
	
		JButton but = new JButton(" View details ");
		but.setPreferredSize(new Dimension(15, but.getHeight()));
  		Icon i = new ImageIcon(this.getClass().getResource("magnifier.png"));
  		but.setIcon(i);
		add (but);

    }
    
	public Component getTableCellRendererComponent (JTable table,
	    Object value, boolean isSelected, boolean hasFocus, int row,
	    int column) {
	return this;
    }
}
