/**
 * Attention: Generated source! Do not modify by hand!
 * Generated by: Merode Code Generator 2.0
 */
package messages;

//All texts, messages, labels should go here
public class MessageProperties {
	

	//============================= general =======================================
	public final static String HELP = "Help";
    
    public final static String INFO = "Information";
    
    public final static String EMPTY_STRING = "<html>&nbsp;&nbsp;&nbsp;</html>";
    
    public final static String VIEW = " View details ";
    
    public final static String LOG =  " Event execution log ";
    public final static String EXPAND =  " show log ";
    public final static String COLLAPSE =  " hide log ";
	
	//============================= listViews =====================================
	public final static String EMPTY_ASSOCIATION = "Doesn't have associated object.";
    public final static String NO_ITEM_SELECTED = "Select object from combobox.";
	public final static String SELECT_TO_VIEW = "select to view...";

	
	//============================= tableViews ====================================
    
    public final static String NO_ROW_SELECTED = "No row is selected from object table.";
    
    public final static String FINAL_STATE_INFO = "A tick symbol in this column indicates\nthat the object is finalized by having reached\nits final state.\nFinal state however doesn't assume physical removal.";
    
    public final static String COLUMN_FINAL = "<html><b>final</b>&nbsp;&nbsp;&nbsp;<img src=\"file:help_small.png\"/></html>";
     
    public final static String COLUMN_CONSISTENCY = "<html><b>consistency</b></html>";
}
